name: 'Publish new release'

on:
  push:
    tags: ['v*']

# This workflow will trigger on each push of a tag that starts with a "v" to create or update a GitHub release, build your app, and upload the artifacts to the release.
# Useful links:
# https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases
# https://github.com/marketplace/actions/rust-release-binary
# https://github.com/cargo-bins/cargo-binstall/blob/main/.github/workflows/release-packages.yml
# https://github.com/trunk-rs/trunk/blob/main/.github/workflows/release.yaml
# https://goreleaser.com/quick-start/

env:
  binary_name: pdf-reader-gpui

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            target: 'aarch64-apple-darwin'

          - platform: 'macos-latest' # for Intel based macs.
            target: 'x86_64-apple-darwin'

          - platform: 'ubuntu-24.04'
            target: 'x86_64-unknown-linux-gnu'

          - platform: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            ext: '.exe'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      # https://github.com/longbridge/gpui-component/blob/b899100d09afa2d3a072b8c7b7364e5e7620f4b5/script/install-linux.sh
      - name: Install dependencies
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          sudo apt update
          # Test on Ubuntu 24.04
          sudo apt install -y \
            gcc g++ clang libfontconfig-dev libwayland-dev \
            libwebkit2gtk-4.1-dev libxkbcommon-x11-dev libx11-xcb-dev \
            libssl-dev libzstd-dev \
            vulkan-validationlayers libvulkan1

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Post Build | Move binary
        run: |
          mkdir uploads
          mv target/${{ matrix.target }}/release/${{ env.binary_name }}${{ matrix.ext }} uploads/${{ env.binary_name }}${{ matrix.ext }}

      - name: Post Build | Prepare artifacts [zip]
        if: matrix.platform == 'windows-latest'
        working-directory: uploads
        run: |
          7z a ${{ env.binary_name }}-${{ matrix.target }}.zip ${{ env.binary_name }}${{ matrix.ext }}

      - name: Post Build | Prepare artifacts [tar.gz]
        if: matrix.platform != 'windows-latest'
        working-directory: uploads
        run: |
          tar --create --gzip --verbose --file  ${{ env.binary_name }}-${{ matrix.target }}.tar.gz ${{ env.binary_name }}${{ matrix.ext }}

      - name: Post Build | Remove binary (now inside compressed artifact)
        working-directory: uploads
        run: |
          rm ${{ env.binary_name }}${{ matrix.ext }}

      - name: Post Build | Display structure of uploads folder
        run: ls uploads

      - name: Post Build | Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.binary_name }}-${{ matrix.target }}
          path: uploads/*
          retention-days: 1
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download binaries from previous job
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls artifacts

      # Upload release asset:  https://github.com/actions/upload-release-asset
      # which recommends:      https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: artifacts/*
